spring:
  application:
    name: microservice-discovery
---
spring:
  profile: discrovery1
server:
  port: 8761
eureka:
  instance:
    host: localhost
  server:
    enable-self-perservation: false
    evicetion-interval-timer-in-ms: 4000
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
---
spring:
  profile: discrovery2
server:
  port: 8762
eureka:
  instance:
    host: localhost
  server:
    enable-self-perservation: false
    evicetion-interval-timer-in-ms: 4000
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
---
spring:
  profile: discrovery3
server:
  port: 8763
eureka:
  instance:
    host: localhost
  server:
    enable-self-perservation: false
    evicetion-interval-timer-in-ms: 4000
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
